---

 - name : update web servers
   hosts : web
   become : yes

   tasks :
   - name : ensure directory is created
     file :
         path : /home/centos/web
         state : directory

   - name : ensure file is updated
     copy :
         dest : /opt/myfile.text
         content : my web app config


 - name : update app servers
   hosts : app

   tasks :
   - name : ensure directory is created
     file :
      path : /home/centos/app
      state : directory

   - name : ensure file is updated
     copy :
         dest : /home/centos/app/app.conf
         content : my app app config
...

